
module.exports = Object.freeze({
    MODAL_BODY_TYPES : {
        USER_DETAIL : "USER_DETAIL",
        USER_ADD_NEW : "USER_ADD_NEW",
        USER_EDIT: "USER_EDIT",
        CATE_ADD_NEW : "CATE_ADD_NEW",
        CATE_EDIT: "CATE_EDIT",
        SUPP_ADD_NEW : "SUPP_ADD_NEW",
        SUPP_EDIT: "SUPP_EDIT",
        PRODUCT_EDIT: "PRODUCT_EDIT",
        PRODUCT_ADD_NEW: "PRODUCT_ADD_NEW",
        CONFIRMATION : "CONFIRMATION",
        DEFAULT : "",
    },

    RIGHT_DRAWER_TYPES : {
        NOTIFICATION : "NOTIFICATION",
        CALENDAR_EVENTS : "CALENDAR_EVENTS",
    },

    CONFIRMATION_MODAL_CLOSE_TYPES : {
        LEAD_DELETE : "LEAD_DELETE",
        CATE_DELETE : "CATE_DELETE",
        SUPP_DELETE: "SUPP_DELETE",
        USER_HIDDEN: "USER_HIDDEN",
        PRODUCT_HIDDEN: "PRODUCT_HIDDEN",
        PRODUCT_DELETE: "PRODUCT_DELETE",
    },
});
